FROM node:16
# Create app directory
WORKDIR /app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json .

# install dependencies
RUN npm install

# Bundle app source
COPY . .

# add environment variables
ENV MY_APP_NAME=myname

RUN npm run build
